/**
 * Parity check: the browser engine must agree with scikit-learn.
 *
 * A silent divergence here would make every verdict in the web app wrong while
 * looking perfectly plausible, so this compares probabilities case by case
 * against predictions generated by Python.
 *
 *   node webapp/test/parity.mjs webapp/test/cases.json
 */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root = path.resolve(import.meta.dirname, '..');
const casesPath = process.argv[2] || path.join(root, 'test', 'cases.json');

// model.js is a browser script (no exports); run it in a context that provides
// the two globals it touches, then lift `Model` out.
const context = {
  performance: { now: () => 0 },
  fetch: async () => ({
    ok: true,
    json: async () => JSON.parse(fs.readFileSync(path.join(root, 'model', 'model.json'), 'utf8')),
  }),
  console,
};
vm.createContext(context);
// `const Model = ...` is lexically scoped, so it never lands on the context
// object. Publish it explicitly rather than changing model.js for the test's sake.
vm.runInContext(
  fs.readFileSync(path.join(root, 'js', 'model.js'), 'utf8') + '\n;globalThis.Model = Model;',
  context,
);
const Model = context.Model;

await Model.load('model/model.json');

const cases = JSON.parse(fs.readFileSync(casesPath, 'utf8'));
let worstProb = 0;
let labelMismatches = 0;

for (const c of cases) {
  const got = Model.predict(c.profile);
  for (const [cls, expected] of Object.entries(c.probabilities)) {
    worstProb = Math.max(worstProb, Math.abs(got.probabilities[cls] - expected));
  }
  if (got.label !== c.label) {
    labelMismatches++;
    console.error(`  label mismatch: expected ${c.label}, got ${got.label}`,
                  JSON.stringify(c.profile));
  }
}

console.log(`cases              : ${cases.length}`);
console.log(`label mismatches   : ${labelMismatches}`);
console.log(`max probability gap: ${worstProb.toExponential(3)}`);

// 1e-6 covers the rounding applied when the JSON was written; anything larger
// means the JS is not reproducing sklearn's maths.
const ok = labelMismatches === 0 && worstProb < 1e-6;
console.log(ok ? '\nPARITY OK — the browser engine matches scikit-learn.'
               : '\nPARITY FAILED');
process.exit(ok ? 0 : 1);
